apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "db-port"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql-sfs
