apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    type: local
    name: app-pv
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
