apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  selector:
    matchLabels:
      type: local
      name: app-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
