apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-server
  template:
    metadata:
      labels:
        app: load-server
    spec:
      containers:
        - name: load
          image: clfray/spring-petclinic-load:24.08.15
          ports:
            - containerPort: 8089
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          command: ["locust", "-H", "http://nginx-service", "--headless"]
          volumeMounts:
            - name: locustfile
              mountPath: /home/locust/locustfile.py
              subPath: locustfile.py
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
